### PR TITLE
Remove dist directory from git repo

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
This package is not on NPM, so we currently install directly from latest commit on Github (see https://github.com/inspirehep/inspire-next/blob/a1231dee4c98fff9253f8cb205d2be7cf4371175/inspirehep/modules/search/bundles.py#L36).

So the `dist/` folder has to be part of the files.

**Comment by kaplun** [comment]
Shall we add it to `npm` then?

**Comment by kaplun** [comment]
Since the `dist` folder is generated, it's a bit tricky to maintain it up-to-date in case of rebase.

**Comment by jmartinm** [comment]
Yes, I can have a look into that and amend `.travis.yml` to publish in npm.

**Comment by jmartinm** [comment]
will be solved in https://github.com/inspirehep/inspirehep-search-js/pull/27

**Pull request closed without merging**
